### PR TITLE
Misc minor improvements

### PR DESCRIPTION
**Pull request by CuleX**
Incorporates:

* some fixes for bugs that gcc caught (array index fail, forgot to actually call a function),
* a `.gitignore` file,
* improving messages (in particular, doing away with obvious typos),
* setting the +6 server flag (future-proofing; L does not actually seem to handle hosts at all),
* making the network name configurable (to avoid misrepresentation).

I've left the O login alone, though it *probably* can be ripped out, as far as I can tell the only command used with O is `auth`, but there's an ifdef guard around the O stuff anyway.

### CODE REVIEW

**Comment by retropc** [comment]
this project is dead -- feel free to fork it and I'll even link to that if you 're going to maintain it, but it's just here for historical curosity

**Comment by CuleX** [comment]
It was worth a shot getting these into upstream, even if the project is dead. Closing PR.

My branch is going to clean up some of the ifdef cruft as needed, clean up with some unused variables and that should be it. If upstream ircu changes P10 in a way it breaks the few things L depends on, I'll update L, presumably with an option to keep old behavior in case snircd does not pull the changes in. I'm not sure if that fulfills your definition of maintenance.

**Comment by retropc** [comment]
the offer is open regardless -- let me know if you want us to link to your repo

for L/O/other old projects we're using github as more of a nice tarball browser interface

**Comment by CuleX** [comment]
@retropc I've made up my mind; I will be maintaining it going forward. Though I doubt dev activity will suddenly spike. lightweight is minimalist by design, after all, so there's not much to do in terms of features, and messing with the internals too much is touching a running system.

However, I'm willing to help people out who do want to use L for whatever reason and I'll probably at least be going through the documentation some more, namely the help files and the HTML manuals (`<meta name="GENERATOR" content="Mozilla/4.7 [en] (Win95; I) [Netscape]">` is not something I wanted to see, however). I'll also keep fixing bugs I come across. What I've said before with regards to keeping in sync with upstream P10 still applies.

Because [commits to forks do not count as contributions on GitHub](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork), I'd be glad if you would allow me to dissolve the fork status on GitHub. A note is already in the repo README that links to the QuakeNet repo.

**Comment by retropc** [comment]
feel free to do whatever you want, subject to the license

I held off on archiving it as I was going to edit the README to possibly link to your repo

we regard this project as dead as newserv replaces its feature set entirely -- we haven't run it for almost a decade we don't expect anyone else to when they could run newserv instead

**Comment by CuleX** [comment]
btw the repo is all ready now, in its own fork network and all.

**Pull request closed without merging**
